version: 1
jobs:
  build:

    working_directory: ~/tesserakt

    docker:
      - image: circleci/10-jdk-node-browsers

    steps:

      - checkout

      - restore_cache:
          key: tesserakt-kt-springbt-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tesserakt-kt-springbt-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/tesserakt-kt-springbt-0.0.1-SNAPSHOT.jar