version: 1
jobs:
  build:

    working_directory: ~/tesserakt

    docker:
      - image: circleci/openjdk:10-jdk-node-browsers

    steps:

      - checkout

      - restore_cache:
          key: tesserakt-kt-springbt-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tesserakt-kt-springbt-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: target/tesserakt-0.0.1-SNAPSHOT.jar

      - setup_remote_docker

      - deploy:
          name: Deploy jar artficat to ECR if branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build . --tag 634462431811.dkr.ecr.us-east-2.amazonaws.com/tesserakt-ecr
              sudo apt-get update --fix-missing
              sudo apt install python-pip python-dev
              sudo pip install awscli
              aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
              aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
              aws configure set default.region us-east-2
              $(aws ecr get-login --no-include-email)
              docker push 634462431811.dkr.ecr.us-east-2.amazonaws.com/tesserakt-ecr
            fi
